version: 0.2

env:
  #variables:
     # key: "value"
     # key: "value"
  parameter-store:
     TWINE_USERNAME: /CodeBuild/TWINE_USERNAME
     TWINE_PASSWORD: /CodeBuild/TWINE_PASSWORD

phases:
  install:
    commands:
       - pip install twine
       - pip install wheel
  #pre_build:
    #commands:
      # - command
      # - command
  build:
    commands:
       - ./upload2pypi.sh
      # - command
  #post_build:
    #commands:
      # - command
      # - command
#artifacts:
  #files:
    # - location
    # - location
  #name: $(date +%Y-%m-%d)
  #discard-paths: yes
  #base-directory: location
#cache:
  #paths:
    # - paths
